/*Copyright (c) 2011, 2022, Oracle and/or its affiliates.  All rights reserved.*/
/*MF:S MF:L*/
try{(function(p,m){function z(){var a={},k=0,c=!1,d="MFPA_"+m.floor(m.random()*m.pow(10,12));this.__d=function(f){if(f&&"object"===typeof f)for(var k in f)f.hasOwnProperty(k)&&(a[k]=f[k])};this.sp=function(f){if(!f||c&&f.LOAD)return!1;f.LOAD?(k=a.e=0,c=!0):f.FALLBACK_LOADED?(a.tc=1,a.e=9,k=1):f.AD_FOUND&&(a.tc=1,a.id=1,a.e=9,k=2);a.g=k;var h;f="";for(h in a)if(a.hasOwnProperty(h)){var b=encodeURIComponent(a[h]);f+="&"+h+"="+b}h=f.slice(1);f=h;b=new p;b=[b.getFullYear(),("0"+(b.getMonth()+1)).slice(-2),
("0"+b.getDate()).slice(-2)].join("-");f+="MOAT_FEATHER_DEBUG1"+b;var e=0;if(0==f.length)f=e;else{for(b=0;b<f.length;b++)var A=f.charCodeAt(b),e=(e<<5)-e+A,e=e&e;f=m.abs(e)}h="https://px.moatads.com/pixel.gif?"+h+"&na="+f+"&cs=0";var u;try{"undefined"!==typeof omidNative&&("undefined"===typeof Image||Image&&Image._MoatProxyOf)?omidNative.sendUrl(h):(u=new Image(1,1),u.src=h)}catch(n){u=new Image(1,1),u.src=h}return!0};this.an=function(){return d}}function w(a,k,c){return a?a&&a.src&&a.src.indexOf&&
(-1!==a.src.indexOf("advancedigitaldfp80721595993/"+k)||-1!==a.src.indexOf("advancedigitaldfp80721595993%2F"+k))?"undefined"!==typeof a[c]&&!0===a[c]?!1:a[c]=!0:!1:!1}function B(a,k){return!k(a.parent)&&!k(a.top)}function C(){var a=!1;try{a=!!window.top.frames[l.pcode+"_MOAT_IFRAME"]}catch(k){}return a}function x(){if(!c.d.g){c.d.g=!0;var a=r,k="scriptfound"+l.pcode,d=m.floor(m.random()*m.pow(10,10)),p=m.floor(m.random()*m.pow(10,12)),f=a.className||"-",h=a.getAttribute("src");h||(h="z.moatads.com/advancedigitaldfp80721595993/moatad.js#");
a={sli:"ADVANCEDDIGITAL_DFP1"};"string"===typeof l.altKey&&(a[l.altKey]=1);"object"===typeof l.dSA&&(a.dSA=JSON.stringify(l.dSA));a.useSlotIkey=l.useSlotIkey;var b;0>h.indexOf("#")&&0>h.indexOf("?")?b="#":(b=h[h.length-1],b="&"!==b&&"#"!==b?"&":"");var e=[];for(key in a)a.hasOwnProperty(key)&&e.push(key+"="+a[key]);b+=e.join("&");h+=b;f=encodeURIComponent(f)+"@@@"+encodeURIComponent(h);window.top.postMessage("MSFAPI#1.2#"+p+"#"+k+"#"+d+"#"+f,"*")}}var c={},l={pcode:"advanceddigitalheader640552616592",
useSlotIkey:!0};(function(a){function k(e){if(null==e||a.a.i(e))return!1;var b=e.length;return 1===e.nodeType&&b?!0:"string"===typeof e||a.a.j(e)||0===b||"number"===typeof b&&0<b&&b-1 in e}var c;a.a={};a.a.a={};a.a.b=function(e){return function(){var b=!1;return function(c){try{return e&&e.apply?e.apply(null,arguments):e(c)}catch(k){if(!b){b=!0;var n=(new p).getTime();this["Moat#ETS"]||(this["Moat#ETS"]=n);this["Moat#EMC"]||(this["Moat#EMC"]=0);var g=36E5<=n-this["Moat#ETS"],f="";try{f=e.toString()}catch(h){f=
"failed"}f=k.name+" in closure (cb): "+k.message+", stack="+k.stack+", \ncb="+f+"\n";if(!g&&10>this["Moat#EMC"]){this["Moat#EMC"]++;try{var d="undefined"!==typeof omidNative&&("undefined"===typeof Image||Image&&Image._MoatProxyOf),m=d?"":document.referrer,v="undefined"===typeof AD_VIEW_HASH?"ADVANCEDDIGITAL_DFP1":AD_VIEW_HASH,l="undefined"!==typeof a&&a.b&&a.b.a?a.b.a:"",t="https://px.moatads.com/pixel.gif?e=24&d=data%3Adata%3Adata%3Adata&i="+escape(v)+"&ac=1&k="+escape(f)+"&ar="+escape("bee2df476bf-clean")+
"&iw="+escape("47748cb")+"&bq="+escape(l)+"&j="+escape(m)+"&cs="+(new p).getTime();if(d)omidNative.sendUrl(t);else{var q=new Image(1,1);q.src=t}}catch(h){}}else if(g){this["Moat#EMC"]=1;this["Moat#ETS"]=n;try{m=(d="undefined"!==typeof omidNative&&("undefined"===typeof Image||Image&&Image._MoatProxyOf))?"":document.referrer,v="undefined"===typeof AD_VIEW_HASH?"ADVANCEDDIGITAL_DFP1":AD_VIEW_HASH,l="undefined"!==typeof a&&a.b&&a.b.a?a.b.a:"",t="https://px.moatads.com/pixel.gif?e=24&d=data%3Adata%3Adata%3Adata&i="+
escape(v)+"&ac=1&k="+escape(f)+"&ar="+escape("bee2df476bf-clean")+"&iw="+escape("47748cb")+"&bq="+escape(l)+"&j="+escape(m)+"&cs="+(new p).getTime(),d?omidNative.sendUrl(t):(q=new Image(1,1),q.src=t)}catch(h){}}}}}}()};a.a.d=function(){if(!c){c=new z;var e={e:0};e.d=a.c.a.moatClientLevel1+":"+a.c.a.moatClientLevel2+":"+a.c.a.moatClientLevel3+":"+a.c.a.moatClientLevel4;e.de=m.floor(m.random()*m.pow(10,12));e.t=(new p).getTime();e.i="MOAT_FEATHER_DEBUG1";e.gw="advancedigitaldfp80721595993";e.cm="1";
e.ac=1;e.f=a.c.b?0:1;e.bq=0;e.ar="bee2df476bf-clean";e.iw="47748cb";a.c.c&&(e.dMoatOQs=a.c.c);a.a.c(e);window[a.a.e()]=c}};a.a.f=function(a){c&&c.sp(a)};a.a.c=function(a){c&&c.__d(a)};a.a.e=function(){return c&&c.an()};a.a.g=function(e){var b={};b.fq=e.HEADER_TRACKING?"1":"0";b.sy=e.HEADER_TRACKING?"1":"0";e.NAMED_IFRAME?(b.gh=1,b.wb=2):(b.gh=0,b.wb=0);a.a.c(b)};a.a.h=function(a){try{var b=a.className,c=a.getAttribute("src");b.split("\n").join(" ");if(-1!==b.indexOf("moatfooter"))return!1;var n=c.split("?"),
g=c.split("#");a=!1;1<n.length&&1<g.length&&n[1].length<g[1].length&&(a=!0);if(1==n.length||a)n=g;if(1<n.length){for(var k=n[1],f,g=k,n={},g=g.replace(/&amp;/g,"&").replace(/(^\s+|\s+$)/g,""),h=g.split("&"),g=0;g<h.length;g++){var d=h[g].split("=");if("string"===typeof d[1]){d[0]&&d[0].match("moatClient")&&(n["rawM"+d[0].slice(1)]=d[1]);a=d;var m,l=d[1],b=l;try{for(c=0;100>c&&(l=decodeURIComponent(l),b!=l)&&!l.match(/^http(s)?\:/);c++)b=l}catch(p){}m=l.replace(/(^\s+|\s+$)/g,"");a[1]=m}else d[1]=
"";n[d[0]]=d[1]}if(h=n){for(var q in h)h.hasOwnProperty(q)&&q&&q.match("moatClientLevel")&&"string"===typeof h[q]&&(h[q]=h[q].replace(/\:/g,"_").replace(/%3A/gi,"_"));n=h}else n=void 0;f=n;f._originalQueryString=k;return f}return!1}catch(p){return!1}};a.a.i=function(a){return a&&a.document&&a.location&&a[d+f]&&a[h+b]};a.a.j=function(e){return(e=a.a.a.toString.call(e))&&("[object Array]"===e||"[object Array Iterator]"===e)};a.a.k=k;a.a.forEach=function(a,b,c,f){var g,d=typeof a;if(a)if("function"===
d)for(g in a){if("prototype"!=g&&"length"!=g&&"name"!=g&&(f||!a.hasOwnProperty||a.hasOwnProperty(g))&&(d=b.call(c,a[g],g),"boolean"===typeof d&&!d))break}else if("number"===d)for(g=0;g<a&&(d=b.call(c,a,g),"boolean"!==typeof d||d);g++);else if("function"===typeof a.every)a.every(function(a,e,d){a=b.call(c,a,e);return!("boolean"===typeof a&&!a)});else if(k(a))for(g=0;g<a.length&&(d=b.call(c,a[g],g),"boolean"!==typeof d||d);g++);else for(g in a)if(f||a.hasOwnProperty(g))if(d=b.call(c,a[g],g),"boolean"===
typeof d&&!d)break;return a};a.a.l=function(a){return a.parentNode||a.parentElement||!1};a.a.hasChildNodes=function(a){return a&&a.childNodes&&0<a.childNodes.length};a.a.m=function(a,b){return!b(a.parent)&&!b(a.top)};a.a.n=function(){return{HEADER_TRACKING:!1,NAMED_IFRAME:!1}};var d="ale",f="rt",h="setInte",b="rval"})(c);(function(a){function c(b,e,d){if(!b)return[];var f="boolean"===typeof d?d:!1,k=[b],g=!1;a.a.forEach("number"===typeof e?e:50,function(){if((g=a.a.l(b))&&1==g.nodeType)b=g,k.push(b);
else if(f&&g&&9==g.nodeType)if((g=a.e.a(b))&&1==g.nodeType)b=g,k.push(b);else return!1;else return!1});return k}function d(b){if(!b)return!1;if("OBJECT"!==b.nodeName&&"EMBED"!==b.nodeName)return b;b=c(b);var e=!1;a.a.forEach(b,function(a){if(a&&"OBJECT"!==a.nodeName&&"EMBED"!==a.nodeName)return e=a,!1});return e}function l(b,e){if(!b||!e)return!1;var c=d(e);if(!c)return!1;if(a.a.hasChildNodes(c)){var f=c.childNodes[m.max(0,c.childNodes.length-1)]||null;c.insertBefore(b,f)}else c.appendChild(b);return c}
function f(a,e,c){"function"===typeof a.addEventListener?a.addEventListener(e,c):"function"===typeof a.attachEvent&&a.attachEvent("on"+e,c)}function h(b){var e=b.indexOf("#"),c=b.indexOf("?");-1===e&&-1===c?b+="#":"&"!==b[b.length-1]&&(b+="&");e="fMoatCb="+a.a.e();return b+e}a.d={};a.d.c=function(b){a.d.b&&"function"===typeof window.clearTimeout&&window.clearTimeout(a.d.b);a.d.b=null;try{window.document.documentElement.removeChild(a.d.a),a.d.a=null}catch(e){}a.a.g(b);a.a.f({LOAD:!0})};a.d.d=function(b,
e){var c=!1,d;d=a.a.b(function(f){if(!c&&f&&f.data&&"string"===typeof f.data&&(f=f.data.match(/MSFAPI#1.2#[0-9]+#header_detector#[0-9]+#(.+)/i))){var g=a.a.n();"1"===f[1]?(g.HEADER_TRACKING=!0,a.d.c(g),b&&b()):(a.d.c(g),e&&e());c=!0;f=window;"function"===typeof f.removeEventListener?f.removeEventListener("message",d):"function"===typeof f.detachEvent&&f.detachEvent("onmessage",d)}});f(window,"message",d)};a.d.e=function(){function b(){if(null===a.d.b)return!1;var b=a.a.n();a.d.c(b);a.d.f()}var c=
!1;try{var d=document.createElement("iframe");d.src="https://z.moatads.com/hd09824092/iframe.html#slot=1";d.style.display="none";d.style.width="0px";d.style.height="0px";d.width="0";d.height="0";c=l(d,window.document.documentElement);a.d.a=d;if("function"===typeof window.setTimeout){var f=a.a.b(b);a.d.b=window.setTimeout(f,2E3)}}catch(k){}c||b()};a.d.f=function(){if(a.d.g)return!1;a.d.g=!0;a.d.h()};a.d.h=function(){var b=document.createElement("script"),c=r.src.replace("moatad.js","moatcore.js");
b.src=h(c);b.onerror=a.a.b(function(a){throw Error("Error loading fallback tag");});a.a.l(r).appendChild(b);return b}})(c);(function(){c.e=c.e||{};c.e.b=function(a,c){};c.e.c=function(a){try{var c=typeof a.location.toString;if("undefined"===c||"unknown"===c)return!0;var d=typeof a.document;if("undefined"===d||"unknown"===d)return!0;var l=a.innerWidth||a.document.documentElement.clientWidth||a.document.body.clientWidth||0;return"number"!==typeof(a.screenX||a.screenLeft||0)||"number"!==typeof l?!0:
!1}catch(f){return!0}}})();var r=function(a){if(!a)return null;var c=a.currentScript;if(w(c,"moatad.js","moatFoundADVANCEDDIGITAL_DFP1"))return c;a=a.getElementsByTagName("script");for(c=a.length-1;-1<c;c--)if(w(a[c],"moatad.js","moatFoundADVANCEDDIGITAL_DFP1"))return a[c];return null}(document);if(r){var d=c.a.h(r);c.c={};c.c.a={moatClientLevel1:"ADVANCEDDIGITAL_DFP1",moatClientLevel2:d&&(d.moatClientSlicer1||"-"),moatClientLevel3:d&&(d.moatClientSlicer2||"-"),moatClientLevel4:d&&(d.moatClientSlicer3||
"-")};c.c.d="ADVANCEDDIGITAL_DFP1";c.c.e=d;c.c.c=d&&d._originalQueryString;c.c.b=B(window,c.e.c);d=c.a.n();c.a.d();if(c.c.b){var y=window.top["__moatSlotTagLoaded"+l.pcode];"function"===typeof y?(d.HEADER_TRACKING=!0,c.d.c(d),l.sli="ADVANCEDDIGITAL_DFP1",y(r,l)):(c.d.c(d),c.d.f())}else C()?(d.HEADER_TRACKING=!0,d.NAMED_IFRAME=!0,c.d.c(d),x()):(c.d.d(x,c.d.f),c.d.e())}})(Date,Math)}catch(p){var GLOBAL_VAR=this,ct=(new Date).getTime();GLOBAL_VAR["Moat#ETS"]||(GLOBAL_VAR["Moat#ETS"]=ct);GLOBAL_VAR["Moat#EMC"]||
(GLOBAL_VAR["Moat#EMC"]=0);var et=ct-GLOBAL_VAR["Moat#ETS"],hourElapsed=36E5<=et,msg=p.name+" in closure (global): "+p.message+", stack="+p.stack;if(!hourElapsed&&10>GLOBAL_VAR["Moat#EMC"]){GLOBAL_VAR["Moat#EMC"]++;try{var pixelDomain="px.moatads.com",isDomless="undefined"!==typeof omidNative&&("undefined"===typeof Image||Image&&Image._MoatProxyOf),documentReferrer=isDomless?"":document.referrer,isBeta=!1,viewHash="undefined"===typeof AD_VIEW_HASH?isBeta?"ADVANCEDDIGITAL_DFP1_BETA":"ADVANCEDDIGITAL_DFP1":
AD_VIEW_HASH,tagType="undefined"!==typeof Moat&&Moat.b&&Moat.b.a?Moat.b.a:"",pxSrc="https://"+pixelDomain+"/pixel.gif?e=24&d=data%3Adata%3Adata%3Adata&i="+escape(viewHash)+"&ac=1&k="+escape(msg)+"&ar="+escape("bee2df476bf-clean")+"&iw="+escape("47748cb")+"&bq="+escape(tagType)+"&j="+escape(documentReferrer)+"&cs="+(new Date).getTime();if(isDomless)omidNative.sendUrl(pxSrc);else{var moat_px=new Image(1,1);moat_px.src=pxSrc}}catch(m){}}else if(hourElapsed){GLOBAL_VAR["Moat#EMC"]=1;GLOBAL_VAR["Moat#ETS"]=
ct;try{pixelDomain="px.moatads.com",documentReferrer=(isDomless="undefined"!==typeof omidNative&&("undefined"===typeof Image||Image&&Image._MoatProxyOf))?"":document.referrer,isBeta=!1,viewHash="undefined"===typeof AD_VIEW_HASH?isBeta?"ADVANCEDDIGITAL_DFP1_BETA":"ADVANCEDDIGITAL_DFP1":AD_VIEW_HASH,tagType="undefined"!==typeof Moat&&Moat.b&&Moat.b.a?Moat.b.a:"",pxSrc="https://"+pixelDomain+"/pixel.gif?e=24&d=data%3Adata%3Adata%3Adata&i="+escape(viewHash)+"&ac=1&k="+escape(msg)+"&ar="+escape("bee2df476bf-clean")+
"&iw="+escape("47748cb")+"&bq="+escape(tagType)+"&j="+escape(documentReferrer)+"&cs="+(new Date).getTime(),isDomless?omidNative.sendUrl(pxSrc):(moat_px=new Image(1,1),moat_px.src=pxSrc)}catch(m){}}};
